version: '3.7'
services:
  brewone:
    image: registry.panim.one/nasa-backend:latest
    restart: always
    environment:
      - NASA_API_KEY=${NASA_API_KEY}
      - DB_HOST=172.17.0.1
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
    - "4050:4000"